### PR TITLE
Fix reading multiple complex data types exception

### LINKED ISSUE #139: Reading multiple complex data types with column number mismatch exception
Execute statement `select * from test_orc` will get column number mismatch exception as below

Error: ArrowError(ExternalError(Execution("Unexpected batch schema from file, expected 4 cols but got 2")), None)

orc file schema:
CREATE TABLE `test_orc`(
  `id` BIGINT COMMENT 'pk', 
  `m` MAP<STRING,STRING> COMMENT 'test read map type', 
  `l` ARRAY<STRING> COMMENT 'test read list type', 
  `s` STRING COMMENT 'string type'
) using orc

Refernce:
https://github.com/kwai/blaze/issues/715

### PR DESCRIPTION
**Pull request by harveyyue**
Fix #139

### CODE REVIEW

File: src/physical_exec.rs [hunk 1]
```diff
@@ -152,12 +152,21 @@ impl FileOpener for OrcOpener {
...
                 .map_err(ArrowError::from)?;
+            // Find complex data type column index as projection
+            let mut projection = Vec::with_capacity(projected_schema.fields().len());
+            for named_column in builder.file_metadata().root_data_type().children() {
+                if let Some((_table_idx, _table_field)) =
+                    projected_schema.fields().find(named_column.name())
+                {
+                    projection.push(named_column.data_type().column_index());
+                }
+            }
```
Comment (Jefffrey) [inline src/physical_exec.rs:169]:
```suggestion
            let projection = builder
                .file_metadata()
                .root_data_type()
                .children()
                .iter()
                .filter(|named_column| {
                    projected_schema
                        .fields()
                        .find(named_column.name())
                        .is_some()
                })
                .map(|named_column| named_column.data_type().column_index());
```

Thoughts on using a more iterator based approach? Could potentially be simplified further.

**Review by Jefffrey — COMMENTED** [review]
Thanks for raising this. CI failures look unrelated, should be fixed by #141 so just need to pull from main.

Could you also include a short explanation for this fix, to help me understand how it fixes the issue?

**Comment by harveyyue** [comment]
> derstand how it
The elements from complex data type like map will take up indexes as below
image

**Comment by Jefffrey** [comment]
> > Could you also include a short explanation for this fix, to help me understand how it fixes the issue?
> 
> The elements from complex data type like map will take up indexes as below image

But how does this relate to the code changes you made?

**Comment by Jefffrey** [comment]
Thanks for this
